export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff1f3",
        "primary": "#0058be",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container-high": "#e6e8ea",
        "outline": "#727785",
        "secondary-fixed-dim": "#b1c6f9",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#b6ccff",
        "tertiary": "#924700",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed": "#ffdcc6",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed": "#001a42",
        "background": "#f7f9fb",
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#2170e4",
        "on-secondary-container": "#405682",
        "tertiary-container": "#b75b00",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#311400",
        "inverse-primary": "#adc6ff",
        "surface-tint": "#005ac2",
        "secondary": "#495e8a",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#ffb786",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c6d6",
        "surface": "#f7f9fb",
        "secondary-fixed": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-fixed-variant": "#304671",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "on-surface-variant": "#424754",
        "primary-fixed": "#d8e2ff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
